// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC62PlVBO3wwsSGjUZTj_rmXKDhbI3mwRk',
    appId: '1:1070376394953:web:0d813a2d8b2aab32b06d18',
    messagingSenderId: '1070376394953',
    projectId: 'icon-database-f9bb9',
    authDomain: 'icon-database-f9bb9.firebaseapp.com',
    storageBucket: 'icon-database-f9bb9.firebasestorage.app',
    databaseURL: 'https://icon-database-f9bb9-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC62PlVBO3wwsSGjUZTj_rmXKDhbI3mwRk',
    appId: '1:1070376394953:web:8b17e5cab1f1a384b06d18',
    messagingSenderId: '1070376394953',
    projectId: 'icon-database-f9bb9',
    authDomain: 'icon-database-f9bb9.firebaseapp.com',
    storageBucket: 'icon-database-f9bb9.firebasestorage.app',
    databaseURL: 'https://icon-database-f9bb9-default-rtdb.firebaseio.com/'
  );

}